// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuyozhdqnsikrqgcgoyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1eW96aGRxbnNpa3JxZ2Nnb3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzQzMzIsImV4cCI6MjA2MDIxMDMzMn0.svf73sEhm2lif_3D_tEzC1_kRJ7zZYF6v_hNA8X96Og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);